### ISSUE TITLE
Escaped `(` in selectors breaks output

### ISSUE THREAD

**Issue by guivr** [LeaVerou/parsel#30] opened 2022-05-15 14:02 UTC
Hi! Thank you so much for this.

I found a bug when using Tailwind.

Selector:
`.mb-\[max\(-70\%\2c -23rem\)\]`

returns token:
```
[
	{
		"type": "class",
		"content": ".mb-\\[max\\(¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶",
		"name": "mb-\\[max\\(¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶¶",
		"pos": [
			0,
			27
		]
	},
	")\\]"
]
```

**Comment by jrandolf** [comment] 2023-03-06 04:35
This selector isn't a proper CSS selector to begin with, but Parsel should at least throw for this case.

**Comment by LeaVerou** [comment] 2023-03-06 15:51
The root cause of the bug is the escaped parens, in fact even a selector like `.\(\)` reproduces the issue, and `.\(` causes an actual error (Opening paren without closing paren), which makes me think they are somehow interpreted literally in the regexes.

This is definitely a bug, thanks for catching it!

@jrandolf Special characters can totally be a part of class or attribute names, they just need escaping.

**Closed** 2023-03-15 16:32 UTC
Labels: bug
